apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  secret.json: |-
    {
      "api_key" : "somesecretgoeshere"
    }
# the pipe |- accepts the json below it and pipes it into secret.json
#kubectl create secret generic mysecret --from-file .\golang\secrets\secret.json